name: synthetic_domain
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision
  - pytorch-cuda=11.8
  - pyg=2.4.0
  - pip
  - pip:
    - torch-geometric==2.3.1
    - torch-scatter==2.1.1
    - torch-sparse==0.6.17
    - torch-cluster==1.6.1
    - diffusers>=0.25.0
    - transformers>=4.37.0,<4.52.0
    - accelerate==0.21.0
    - safetensors==0.3.1
    - tqdm>=4.65.0
    - pillow>=10.0.0
    - huggingface_hub>=0.20.0
    - numpy>=1.24.0
    - scipy>=1.10.0
    - ftfy>=6.1.1
    - regex>=2023.6.3
    - clip @ git+https://github.com/openai/CLIP.git@main
    - supervision>=0.22.0
    - git+https://github.com/IDEA-Research/GroundingDINO.git
    - opencv-python>=4.8.0
    - timm==0.9.2
    - addict>=2.4.0
    - pycocotools>=2.0.6
    - yapf>=0.40.1
    - charset-normalizer>=2.0.0
    - pyOpenSSL>=23.2.0
    - requests>=2.31.0
    - urllib3>=1.26.16
    - setuptools>=68.0.0
    - wheel>=0.40.0 